name: "Check permission"
description: "Permission check for current github actor to see if it has write access"
inputs:
  user: 
    description: 'user to be checked'
    required: true
  github-repo:
    description: 'github repository'
    required: true
  github-user: 
    description: 'github user for authenticating api requests'
    required: true
  github-passwd:
    description: 'github passwd for authenticating api requests'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
